language: c

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - pip install --user cpp-coveralls
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks make rockspecs/lua-curl-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

before_script:
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls
  - luarocks show lunitx           || luarocks install lunitx
  - luarocks show luafilesystem    || luarocks install luafilesystem
  - luarocks show dkjson           || luarocks install dkjson --deps-mode=none

script:
  - cd test
  - lua -e "print(require 'cURL.utils'.find_ca_bundle())"
  - lunit.sh run.lua
  - lua test_pause02.c.lua
  # - lunit.sh test_easy.lua
  # - lunit.sh test_safe.lua
  # - lunit.sh test_form.lua
  # - lunit.sh test_curl.lua

after_success:
  - coveralls -b .. -r .. --dump c.report.json
  - luacov-coveralls -j c.report.json -v

notifications:
  email:
    on_success: change
    on_failure: always
